### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by jigneshnitsan** [NetConsultAG/netc_bakershop#1]
1. When user add any product to cart, it should ask for two option as in the current site
2. If user clicks on go to cart, We need to show list of products that were added in cart
3. Cart can be updated with Products quantity 
4. We need to show a Cart in menu with number products in cart

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have resolved all the parts, Just one point is pending now, The Update cart is not working properly, So by tomorrow we will resolve this issue.
And then we will update you with some more Q/A.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

We have resolved the last mentioned issues. So please check this at your end.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

1. When user add any product to cart, it should ask for two option as in the current site
Status: Done
Screenshot: http://prntscr.com/bv53h7
Video File: http://recordit.co/QziNA5cEIx

2. If user clicks on go to cart, We need to show list of products that were added in cart
Status: Done
Screenshot: If Product Available > http://prntscr.com/bv551z , If no available > http://prntscr.com/bv55k2

3. Cart can be updated with Products quantity
Status: Done
Screenshot:
Cart Iteam > http://prntscr.com/bv57y3
Once Update: http://prntscr.com/bv58q3
More times Updated: http://prntscr.com/bv59ig , http://prntscr.com/bv5a3h , http://prntscr.com/bv5amv , http://prntscr.com/bv5bl4

4. We need to show a Cart in menu with number products in cart
Status: Done
Screenshot: BE: http://prntscr.com/bv89bh , http://prntscr.com/bv89fn
FE: http://prntscr.com/bv8afz

Regards.

**Comment by michelrossier** [comment]
That looks good, thanks.
