### ISSUE TITLE
Shipping address not saved

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#10]
I just submitted an order in the shop and filled out shipping and billing address. But in the backend I cannot find now the shipping address at all.

That's what I see in the backend: 
http://screencast.com/t/saOZ5rEgOLrQ

The billing address is added under "Shipping" (which is wrong also), but the fields above are all empty. I can't find the shipping address.

You can check that out in http://dev.swissbaker.netconsult.ch/ the last order.

**Comment by jigneshnitsan** [comment]
Hello Michel

Status > Done
Screenshots - http://awesomescreenshot.com/05861x0h02
- http://awesomescreenshot.com/01761x0j44

Regards.

**Comment by michelrossier** [comment]
Thanks, that's good!
