### ISSUE TITLE
Billing address and shipping address should be shown on the last page before the order and in the confirmation e-mail

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#11]
On the page before the user finally submits the order, there should be the billing address shown as well:
http://screencast.com/t/PqGio8G0iRql

The reason is: The user shall have the possibility to check everything he entered for a last time before he sends the order defenitely.

And secondly also important:
Please show both addresses also in the e-mail that the user receives after ordering. That way the user has a reference for what he entered in the shop. 

Thanks for your efforts!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot > http://www.awesomescreenshot.com/0df61yw411
Screenshot > http://www.awesomescreenshot.com/0b961yx747

Regards.

**Comment by michelrossier** [comment]
Thanks, this looks good!
