### ISSUE TITLE
Localization: Still hardcoded texts

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#12]
I found in the file /Resources/Private/Template/Products/List.html this hardcoded text twice: "in den Warenkorb"

and in /Resources/Private/Template/Products/Addtocart.html 
`<f:form.submit value="Update" name="update" />`
The value "Update" needs to be localized too.

Also in the same file there is:
`<f:form.submit value="Submit" />`
This value needs to be localized as well.

Please check again for hardcoded texts. The shop needs to be multilingual. Thanks!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Comment > We have added localized for all points, Please let us know if you find at any particular page.

Regards.

**Comment by michelrossier** [comment]
Thanks, for now this seems fixed. We didn't find any other hardcoded text.
