### ISSUE TITLE
"Prod Attributes" : input instead of select box

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#14]
- List > Products > new product > "Prd Attributes" : 
User should be able to add attributes in an input field and not chosing them from a select box. Meaning, the user can define whatever he wants as the attribute value.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Comment > Your suggestion is also good, But to avoid duplication and continue dynamic both process we have added Insert options with the select box see this screenshot - http://awesomescreenshot.com/02362dv28c
So Admin can also select the existing entry and also can add a new one from there. 

Please check this and let's know your feedback for the same.

Regards.

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 

Thanks for your suggestion. I like it but we do need to implement it as an input field. So the user can chose what he wants. The feedback is that else the list of choice can become too long if there are many product variants to chose from.

Can you put an input field instead of the select box?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot > http://awesomescreenshot.com/0bf62mnz1f
Comments > As per our last discussion we have implemented this. So user can easily write and find the current available attributes and also can add a new one from here.  And we can also achieve the re-usability concept with avoiding high risk of duplication of records.

Please review this and let us know your feedback for the same.

Regards.

**Comment by michelrossier** [comment]
Thanks, can you also commit this to the github version? 

Also: We noticed that the input field is visually a bit below the other fields:
http://screencast.com/t/DlUZGoMWwv

Can you align that, so that everything is on the same height?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

 - Actually it looks because of the default design of TYPO3 Back End.  You can see there is Top Padding given to that element, Which is by default from TYPO3.

 - We have tried to remove and set proper design from other ways like hook and other, but unfortunately there are not any such things.

- It can be possible if we change CSS from core file, But it's not correct way - http://prntscr.com/c30d18

Please let us know your feedback for the same.

Regards.
Thank You.

**Comment by michelrossier** [comment]
Okay, then we let the visual appearance stay as it is. Thanks.

**Comment by michelrossier** [comment]
We tested this, it works as expected. Thank you!
