### ISSUE TITLE
Option to define one image as "Default image" 

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#15]
We need an option to define one image as "Default image" when the user uploads more than one image, so that the marked image is displayed in the thumbnail.

If you have any other mechanism in place already that does that, let me know.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

- Set as Default Image
Comment > We have added this option but I guess it's not with the standard way. @angeloprevitali has suggested a way but this is done in an Extension which we have to analyze first and need to implement it too. Which might take more than 5-7 Hours.

So, My question if it's too much important then we can check now, Else If not important then let's check after all current issues completed.

Let me know your feedback for the same.

Regards. 
Thank You.

**Comment by michelrossier** [comment]
Thanks for the feedback.

Okay, let's put this request on the side. But one question, can you confirm that the current setup always shows the first image as default image for the list view?

I mean: If the user defines multiple images in a product, is then always the first image shown for the list view? Or is it any other image?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Thank you for your message.

Currently it'll always show fist image as default. So if you want to change this then you can just drag and drop any image at first position
Please checkout following screenshots.
- http://awesomescreenshot.com/0a262hm970, http://awesomescreenshot.com/03462hmd28
- http://awesomescreenshot.com/00662hmjec, http://awesomescreenshot.com/02162hmn35
- http://awesomescreenshot.com/0bf62hmv7b, http://awesomescreenshot.com/09f62hn357

Don't hesitate to ask if you have any queries regarding this.

Regards.

**Comment by michelrossier** [comment]
Thank you that is great like that. It works.
