### ISSUE TITLE
List > Products > new product > "Dont show in list" : should not be activated by default

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#16]
- List > Products > new product > "Dont show in list" : should not be activated by default

Currently when you create a new product, the option "Dont show in list" is marked. But this should be deactivated as most products will be shown in list. 

Thank you

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot > http://awesomescreenshot.com/00562e8m56 

Regards.

**Comment by michelrossier** [comment]
Perfect, thanks.
