### ISSUE TITLE
RealURL not working if choosed cart

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#17]
If you click on the cart the RealURL is not configured correctly.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot > http://prnt.sc/c1006o

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali
 
For the realurl changes please get code from attachment file and replace the code with /typo3conf/realurl_conf.php

[realurl_conf.txt](https://github.com/NetConsultAG/netc_bakershop/files/399734/realurl_conf.txt)


Regards.

**Comment by angeloprevitali** [comment]
Works ok so far. Please fix the URL that has too much /// in the link. Can you please fix this, too? Thanks.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot > http://prnt.sc/c1xdlw

Regards.

**Comment by angeloprevitali** [comment]
Hello 

Please DO NOT change the actual RealURL like this with endings with .html.
Please fix the RealURL to keep the links as usual with endings like /de/shop/

Thanks.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot > http://prntscr.com/c31cx8
Comments > Actually by mistake we enable the custom extension line from the RealURL config. I apologies for your inconvenience.

Regards.

**Comment by angeloprevitali** [comment]
Hello

I just uploaded your latest RealURL conf from dev but now there is a // too much on the product page again.

http://prntscr.com/c31wi8

Can you please fix that?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot:
http://prntscr.com/c3w0iq , http://prntscr.com/c3w4lw , http://prntscr.com/c3w52x , http://prntscr.com/c3w5cd , http://prntscr.com/c3wbvs

Regards.
