### ISSUE TITLE
Show cart keeps navigation in first menu of a product

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#18]
If you add an Item for adding it in the cart the navigation on the left side keeps the product menu active. It should keep the cart menu in the left navigation active.

http://prntscr.com/c0yzoq

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

I need to confirm one thing on this, You mean whenever user clicks add to cart button from the category pages/product pages and go to Cart page at that time only Parent menu in our case Promoshop should be active. We don't need to show "Verkaufstafeln" as active menu. See this screenshot - http://prntscr.com/c14d2y

Please let me know your reply for the same.

Regards.

**Comment by michelrossier** [comment]
Jignesh, a small change in this request: Is it possible to have the Page "Warenkorb" which is the cart page, to show this active as soon as the user enter the cart.

I just saw that on the dev page this already works like that. But in our environment, see here:
http://swissbaker.netconsult.ch/de/ueber-uns/promoshop/aktuelles/

This is  not the case. We would like to have it that way that when a user adds a product to the cart, that the page "Warenkorb" which is the cart, is shown active. 

Can you do that? Thanks

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Please checkout following steps to make Active cart page - http://awesomescreenshot.com/0de62ho49f
1. Drag original page and make new page - http://awesomescreenshot.com/03d62hoz74
2. So pages looks like as - http://awesomescreenshot.com/00962hp3d2, http://awesomescreenshot.com/03a62hp598
3. Make changes for shortcut page - http://awesomescreenshot.com/00f62hpdb2

Then you can see Active cart page functionality like - http://dev.swissbaker.netconsult.ch/de/shop/cart/addtocart/Products/

Please let me know if you have any question regarding this.

Regards.

**Comment by michelrossier** [comment]
This seems to work without us changing anything after the update. I guess it is okay.
