### ISSUE TITLE
Localization of products is not possible

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#19]
We wanted to translate a product in french and realized that there is no way in doing that. Localization seems not to be enabled for the extension. Please treat this with high priority that we can translate products and all shop elements (e.g. categories etc.) into french.

Thanks.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot-FE > http://awesomescreenshot.com/09162fge94
Screenshot-BE > http://awesomescreenshot.com/0b762fgif1

Regards.

**Comment by michelrossier** [comment]
Perfect, thanks!
