### ISSUE TITLE
Not possible to show cart in Firefox and Internet Explorer when cache is enabled

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#20]
After updating to the latest version and adding a product to the cart, it is not possible to go to the cart page on Internet Explorer and Firefox. Strangely it works in Chrome. Altough it works in all browser if the page cache (page settings > Behaviour) is disabled. Can you fix this that it works when the cache is enabled?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Thank you for your message.

Generally for Dynamic custom site and especially for E-Commerce site the Cache should be disabled for some of the important pages like Product Detail, Cart, Checkout etc... 
So I would suggest to disable the Cache for this also. 

Can you please let me know your feedback for the same?

Regards.

**Comment by michelrossier** [comment]
Okay, we go here with your suggestion and will disable the cache.
