### ISSUE TITLE
Paging of category pages is not real url optimized

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#21]
If you have many products on a page, the paging appears, but when you click to go further in the paging, the URLs are not real url optimized.

Example URL:
http://swissbaker.netconsult.ch/de/ueber-uns/promoshop/aktuelles/

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
URL > http://dev.swissbaker.netconsult.ch/de/shop

Regards.

**Comment by michelrossier** [comment]
Thanks, what I notice is that the URL contains many "/" signs:

http://dev.swissbaker.netconsult.ch/de/shop////2/

Can this be fixed?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

RealURL
Status > Done


Regards.

**Comment by michelrossier** [comment]
Where can we find the updated real url conf regarding this? On our production environment, we still have the /// in the url. 

Thanks.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Please replace latest file of RealURL from http://dev.swissbaker.netconsult.ch [path => /typo3conf/realurl_conf.php]

Please let me know if you are still finding any issues here.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

is THAT RealURL configuration really correct like this? I personally think that fixing this with hardcoded PHP code isn't the right way to create pretty nice urls...

Please advice!

$page = $GLOBALS['TSFE']->page['title'];
$page = str_replace(' ', '-', $page);
$TYPO3_CONF_VARS['EXTCONF']['realurl']['encodeSpURL_postProc'] = array('user_encodeSpURL_postProc');
$TYPO3_CONF_VARS['EXTCONF']['realurl']['decodeSpURL_preProc'] = array('user_decodeSpURL_preProc'); //

function user_encodeSpURL_postProc(&$params, &$ref) {
    for ($i=2; $i < 99; $i++) { 
        $params['URL'] = str_replace($page.'////'.$i, $page.'/'.$i, $params['URL']);
    }
}

function user_decodeSpURL_preProc(&$params, &$ref) {
    for ($i=2; $i < 99; $i++) { 
        $params['URL'] = str_replace($page.'/'.$i, $page.'////'.$i, $params['URL']);
    }
}

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Yes, Absolutely fine to have this. There is not any issues, Please checkout this URL - https://stmllr.net/blog/hiding-repeated-segments-with-realurl/ 
for more info.

Don't hesitate to ask if you have any queries regarding this.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello 
thanks. I implemented it on our live server but now there are // on the product pages again.

See https://github.com/NetConsultAG/netc_bakershop/issues/17#issuecomment-238217752

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot:
http://prntscr.com/c3w7ih , http://prntscr.com/c3w7qe , http://prntscr.com/c3w839 , http://prntscr.com/c3wd9n

Regards.

**Comment by angeloprevitali** [comment]
Hello

we got a problem concerning your "hardcoded" RealURL configuration like described last week in this ticket https://github.com/NetConsultAG/netc_bakershop/issues/21#issuecomment-238214338

Problem is, that by leaving this part of code in the realurl_conf.php-file

```
$page = $GLOBALS['TSFE']->page['title'];
$page = str_replace(' ', '-', $page);
$TYPO3_CONF_VARS['EXTCONF']['realurl']['encodeSpURL_postProc'] = array('user_encodeSpURL_postProc');
$TYPO3_CONF_VARS['EXTCONF']['realurl']['decodeSpURL_preProc'] = array('user_decodeSpURL_preProc'); //

function user_encodeSpURL_postProc(&$params, &$ref) {
for ($i=2; $i < 99; $i++) {
$params['URL'] = str_replace($page.'////'.$i, $page.'/'.$i, $params['URL']);
}
}

function user_decodeSpURL_preProc(&$params, &$ref) {
for ($i=2; $i < 99; $i++) {
$params['URL'] = str_replace($page.'/'.$i, $page.'////'.$i, $params['URL']);
}
}
```

the tx_news paging of the news items will work CORRECTLY! If the code is "active" the tx_news paging will NOT work ANYMORE.

Can you please fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status** > Done
**Screenshots** > http://prntscr.com/c6scz4, http://prntscr.com/c6sd4g
**Comment** > We have checked this, It seems the issue was with the variable. It wasn't fetching Cart Page title dynamically. So we have modified it. Please find the following modified code for this.

$TYPO3_CONF_VARS['EXTCONF']['realurl']['encodeSpURL_postProc'] = array('user_encodeSpURL_postProc');
$TYPO3_CONF_VARS['EXTCONF']['realurl']['decodeSpURL_preProc'] = array('user_decodeSpURL_preProc'); //
function user_encodeSpURL_postProc(&$params, &$ref) {
    $pageTitle = $GLOBALS['TSFE']->page['title']; 
    $pageTitle = strtolower($pageTitle);    
    for ($i=2; $i < 99; $i++) { 
       $params['URL'] = str_replace($pageTitle.'////'.$i, $pageTitle.'/'.$i, $params['URL']);
    }
    $params['URL'] = str_replace("/list/Products//", "/", $params['URL']);
}
function user_decodeSpURL_preProc(&$params, &$ref) {
    $res = $GLOBALS['TSFE']->siteScript;
    $basename = basename(dirname($res));
    $basename = strtolower($basename);
    
    if($basename!='page'){
        for ($i=2; $i < 99; $i++) { 
            $params['URL'] = str_replace($basename.'/'.$i, $basename.'////'.$i, $params['URL']);
        }
    }
}

Please let me know your feedback for the it.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. works. Thanks.
