### ISSUE TITLE
Products are not indexed in indexed search

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#22]
Products are not indexed in index search after opening the product detail page. Please consider in this topic also that it should be possible to serach the products also localized.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Okay, I think this is the same as like here - https://github.com/NetConsultAG/netc_bakerlist/issues/17#issuecomment-237181020 
Here we also need to get the record with Indexed search. We are thinking to use the Crawler but as @angeloprevitali  has mentioned that it's having compatibility issues to TYPO3 CMS Version 8.x. we shouldn't use it. 
So let's complete the issue first in BackerList first and then we will also perform the same here.

What do you think?

Regards.

**Comment by michelrossier** [comment]
Okay, lets do it that way. First you solve it in the bakerlist, then apply the solution to the bakershop.

For us it is important that this is not solved with the crawler. But as a hint, can you check the metaseo extension, there they have exactly this issue solved.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Please refer this - https://github.com/NetConsultAG/netc_bakerlist/issues/17#issuecomment-237841695

Regards.

**Comment by angeloprevitali** [comment]
We let this point/issue currently as is. Thanks.
