### ISSUE TITLE
bakershop_showcart link opens in new page and displays wrong page

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#23]
Two issues we have currently with bakershop_showcart:

- In netc_bakershop_showcart if real url is enabled and page cache activated, if you click on the link to go to the cart, it displays no cart, but a product category page.

You can test this here in the right sidebar:
http://swissbaker.netconsult.ch/de/ueber-uns/promoshop/aktuelles/

Any idea what the issue could be?

- In netc_bakershop_showcart (the element that shows the link to the cart in the sidebar) when you click on the link to go to the cart, it opens the page in a new window. Can you make that this opens right in the same window instead?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot > http://prntscr.com/c1fzkq , http://prntscr.com/c1fzpa
Video File > http://recordit.co/64rWYshLsl

Regards.

**Comment by michelrossier** [comment]
Perfect, thanks.
