### ISSUE TITLE
French Mailtemplates still in use

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#24]
We just tested the french localization and everything seems to work, we can add a product to the cart and go through the cart process, but as soon as you submit the order finally, this error occurs:

Template could not be found at "/home/httpd/vhosts/netconsult.ch/swissbaker.netconsult.ch/typo3conf/ext/netc_bakershop/Resources/Private/Templates/Mail/fr_admin_mailTemplate.html".

We did delete this template (and also the one for the customer) as we assumed that everything is based now on the LLL translation integration in the main template. Isn't this the case?

It still seems to be defined here:
```
C:\Users\michel\Desktop\comparefolderdonaf\netc_bakershop-live\Classes\Controller\ProductsController.php:
  569  
  570  			if($GLOBALS['TSFE']->sys_language_uid == 1){
  571: 				$adminMailTemplateFileTitle = 'fr_admin_mailTemplate';
  572  				$userMailTemplateFileTitle = 'fr_mailTemplate';
  573  			}else{

```

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshots FR
- http://awesomescreenshot.com/05f62kwt73
- http://awesomescreenshot.com/09162kwy50

Screenshots DE
- http://awesomescreenshot.com/05e62kx6f8
- http://awesomescreenshot.com/06c62kx79e

Regards.
Thank You.
