### ISSUE TITLE
SQL error when calling up products in FE

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#25]
Hello

When calling up products there is an SQL error in the BE coming:

exec_SELECTquery
caller TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery
ERROR Table 'swissbaker.tx_netcbakershop_domain_model_emailtemplates' doesn't exist
lastBuiltQuery SELECT uid,t3ver_wsid FROM tx_netcbakershop_domain_model_emailtemplates WHERE 1=1
debug_backtrace require(typo3/sysext/lowlevel/dbint/index.php),typo3/mod.php#32 // TYPO3\CMS\Lowlevel\View\DatabaseIntegrityView->main#26 // TYPO3\CMS\Lowlevel\View\DatabaseIntegrityView->func_refindex#208 // TYPO3\CMS\Core\Database\ReferenceIndex->updateIndex#305 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#1125 // TYPO3\CMS\Core\Database

Can you please fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Comment > Actually right now in GitHub Extension package there were some unnecessary files are there. So we need to remove those files. For now please remove following files.

File Path -  /typo3conf/ext/netc_bakershop/Configuration/TCA/

1.tx_netcbakershop_domain_model_emailTemplate.php
2.tx_netcbakershop_domain_model_config.php

So please check after removing this files.

FYI - We will also provide you list of files which are no more needed in the extension.

Regards.
