### ISSUE TITLE
Translated product with product attributes doesn't load on frontend

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#26]
Hi

When I create a product and translate it, it all works fine. But as soon as a product has at least 1 prod attribute, it doesnt work anymore in the translated language.

Example (product called "test" without image):
http://dev.swissbaker.netconsult.ch/fr/ueber-uns-fr/promoshop-fr/werbung-fr/

Here the product has 1 attribute. In german this still works fine, but in french you cannot open the page anymore of the product.

Can you look into that and fix it asap?  Thank you.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status > Done
Screenshot > http://awesomescreenshot.com/0d662ye6e7
Screenshot > http://awesomescreenshot.com/01a62yey36
Comment > You must translate all the things means all the relation then you see it in FE

Regards.

**Comment by michelrossier** [comment]
Thank you very much, it works!
