### ISSUE TITLE
Translated image alt and title texts are not displayed

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#27]
If you add an image alt- and title-text attributes, then at any time only the german alt- and text attributes are shown.

Example:
http://dev.swissbaker.netconsult.ch/fr/ueber-uns-fr/promoshop-fr/werbung-fr/?tx_netcbakershop_netcbakershop%5Bproducts%5D=23&tx_netcbakershop_netcbakershop%5Baction%5D=show&tx_netcbakershop_netcbakershop%5Bcontroller%5D=Products&cHash=81690ebac2dd840b1f8181d8b7dbfad3

Here we entered in germand and in the french version a text, but only the german text is shown when the french page is loaded.

Please make sure that all parts of the products are shown as entered in the backend.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

We have checked this issue, It seems it's typo3 core issue, So it's taking time to resolve the issue.
See following links for more info.
- https://forge.typo3.org/issues/57272
- https://forge.typo3.org/issues/62127
- http://typo3-english.typo3.narkive.com/POueSekt/extbase-fal-vs-localisation-translations

So we are trying to resolve this issue. 

Regards.
Thank You.

**Comment by michelrossier** [comment]
Okay, thanks, we let it be for the moment.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

As per our comment in this issue - https://github.com/NetConsultAG/netc_bakershop/issues/31#issuecomment-245545493

Please install the extension then there will not be any issues.

Please checkout following screenshots.
DE: BE: http://prntscr.com/cfjilg , FE: http://prntscr.com/cfjj4m , http://prntscr.com/cfjiuu
FR: BE: http://prntscr.com/cfjjcs , FE: http://prntscr.com/cfjjkz , http://prntscr.com/cfjjrw

Regards.
Thank You
