### ISSUE TITLE
Only 1 e-mail template is used

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#28]
Currently for both, the e-mail that the user receives and the one that the admin receives, the system uses each time the same template.

But the specification is that the admin should get a different e-mail than the normal user who orders. There are two e-mail templates in the templates folder, but only the one for the customer is used at any time.

Please fix this that the admin mail is generated with the admin template. Thank you.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status: Done
Screenshot-DE-Admin Email: http://prntscr.com/c4cddk
Screenshot-DE-Customer Email: http://prntscr.com/c4cdku

Screenshot-FR-Admin Email: http://prntscr.com/c4celp
Screenshot-FR-Customer Email: http://prntscr.com/c4cesv

Regards.

**Comment by michelrossier** [comment]
Thank you, that works.
