### ISSUE TITLE
Prod Attributes should show only language translated attributes and remove the + sign

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#29]
Two things with the Prod Attributes:

1. Is it possible that the user only sees the localized product attributes? Currently the user sees all product attributes from all languages. If the user creates for example a french product tranlsation, he should only see the prod attributes.

2. We realized that if the user creates a new category on the product page in the backend by using the + sign, then the localized category doesn't work without the user leaving the product creation page and list all the cateogries and then localizes the category. So that workflow doesn't make sense that the user has to leave the product creation page to localize the category. So we think we have to remove the + sign and the user has to create new categories on the list page overview before creating a product.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

1. 
Status > Done
Screenshot > http://prntscr.com/c69dvk

2. 
Comment > Actually here we have not found any + sign from which we can add the Category. Can you please give some screenshots or video that could suggest more?

Regards.

**Comment by michelrossier** [comment]
Hi Jignesh, thanks for your feedback! The + sign is the one right on your screenshot on the right hand side of the "Find records" field.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Thank you for your reply.

Hmmm, I guess here we have slight misunderstanding. Actually what you have mentioned are Attributes. They are not Categories. We were looking for the Category :)

But now we have removed it. Please check this screenshots - http://awesomescreenshot.com/02d63a9953, http://awesomescreenshot.com/06c63a9b50

Regards.

**Comment by michelrossier** [comment]
That's perfect, thank you!
