### ISSUE TITLE
Adding multiple categories per product

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#30]
Hi

In the bakershop extension currently the user can define only one category per product. The customer wishes that he can add multiple categories per product. So that the product appears in multiple categories (pages) at the same time.

http://content.screencast.com/users/michel.rossier/folders/Snagit/media/aaf5da5d-785a-4301-ba1c-67759a1429db/08.31.2016-13.24.png

Can you program this option?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

We have checked this task and it seems it would be possible. So we will work on this by tomorrow and will update you for the same.

Regards.
Thanks.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

We have completed this. Please check our update as following.

Status: Done
Screenshot:
Product: QA Test 1
BE: http://prntscr.com/cd5xvj , http://prntscr.com/cd5yho
FE: http://prntscr.com/cd5xsn , http://prntscr.com/cd5y1a , http://prntscr.com/cd5z9j , http://prntscr.com/cd5y7q , http://prntscr.com/cd5yaz ,

Product: T-Shirt - Z1
BE: http://prntscr.com/cd618s
FE: http://prntscr.com/cd61b9 , http://prntscr.com/cd61er , http://prntscr.com/cd61kd

Produuct: T-Shirts - Z4
BE: http://prntscr.com/cd85xf
FE: http://prntscr.com/cd860k , http://prntscr.com/cd864w , http://prntscr.com/cd869g

Please review this and let us know your feedback for it.

Regards.

**Comment by michelrossier** [comment]
Thanks, this is perfect.
