### ISSUE TITLE
Bug: When customer defines a different image in french, it doesn't show up

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#31]
The customer reported a bug in the bakershop extension. (This has nothing to do with the recent update of the categories options, it must have existed before).

When a product is created and for the default language an image is defined and for the translation of the product a **different** image, then in the second language the image is not shown at all.

Example:
http://dev.swissbaker.netconsult.ch/de/shop/clothing/show/Products/t-shirt-beck-herren/

Here for french we defined a **different** image and it is not displayed at all:
http://dev.swissbaker.netconsult.ch/fr/shop/clothing/show/Products/t-shirt-beck-herren/

Can you fix this bug as soon as possible?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

We have checked this issue, It seems we have already faced this one, Please check here - https://github.com/NetConsultAG/netc_bakershop/issues/27#issuecomment-239782853

If we have to work on it then It will take much more time and also as this is Core TYPO3 issue may be it can't be resolved.

Can you please share your thoughts on this?

Regards.
Thank You.

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 

Thanks for your fast feedback! Highly appreciated. I was thinking in the #27 it was just the "alt text". But as it turns out it is the whole image that cannot be displayed in a different language. Now I understand.

This is quite a crucial part of the whole thing, the reason is that the customer has images that have text in German and in French that has to be shown in each language. 

Two questions:

1. Have you seen the latest comments about this issue that people reported:
https://forge.typo3.org/issues/57272#note-46
https://forge.typo3.org/issues/57272#note-81

Not sure if that is relevant to the 6.2 version we are running here.

2. Do you think it is okay if I tell the customer that he can continue to create new products and adding the french images (just they are not shown currently) and when we have a solution, they will be displayed automatically without changes?

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Thank you for your message.

@Image Issue
Yes, Now it's a critical issue. Let's try to resolve this.

@Questions
1. No, Yet we have not seen this comments. But we will check this comments and try to resolve this issue asap.

2. Hmm, I am not sure that there will be not any DB changes required. So I think we should wait for at least 1 day. So if there is any changes needed we can adapt it.

Tomorrow we will try to resolve this issue and updates you whatever results we have.

Regards.
Thank You.

**Comment by michelrossier** [comment]
Thank you @jigneshnitsan thanks for your feedback. Okay, I will tell the customer to wait with adding more content to the shop.

Thanks again.

Best regards,
Michel

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

Status: Done
Comment > You have to upload and enable new extension "faltranslation" then only this issue will not be there. We have installed this extension and it's working fine. Please check our following screenshots.
Screenshot: 
DE: BE: http://prntscr.com/cfjcrm , FE: http://prntscr.com/cfjd56 , http://prntscr.com/cfjed7
FE: BE: http://prntscr.com/cfjcz5 , FE: http://prntscr.com/cfjdc6 , http://prntscr.com/cfjehm

Please review this and let us know your feedback on it.

Regards.
