### ISSUE TITLE
RealURL not working for single product on EXT:netc_bakershop (urgent!)

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#35]
If you call up a detail page like http://swissbaker.netconsult.ch/fr/ueber-uns-fr/promoshop/publicite/tableaux-de-vente/show/Products/kundenstopper-a1-beck/ the website gives an "oops" error!

**Please fix it urgent!!!** 

Our customer experience a lot of errors due to this error.

On the DEV website on dev.swissbake.netconsult.ch RealURL for the EXT:netc_bakershop seems NOT TO BE CONFIGURED! WHY???

Thanks.

**Comment by nitsan-technologies** [comment]
Hello Angelo

Please find our comment as following.

**Comment** > The issue is the pageID is not included in the RealURL config file. We have to add the pageID here - http://prnt.sc/ct8fo0

So please add the PageID in the RealURL config file then it will work properly. 
You can see in Dev server now it's working, See this: http://prnt.sc/ct8fkz

Please review this and let's know your feedback for the same.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Sanjay

thanks for answer. I will check this.

BUT HOW CAN THE CUSTOMER add this line into the RealURL conf every time he would like to add a new page??? This is not possible.

Thanks for replay.

Regards,
Angelo

**Comment by angeloprevitali** [comment]
I checked the RealURL PID as in the http://prnt.sc/ct8fo0 described. BUT the problem is still present! What we are talking is that the RealURL will not work IF THE PRODUCT PAGE is leading in the third level of the sublevel. 
![realurl](https://cloud.githubusercontent.com/assets/17588253/19349417/2adc0e28-9153-11e6-8cc4-c4b64b8e2e60.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message.

We have checked same things in Dev server, Where all working perfectly. 
Please check following screenshots
1. http://prntscr.com/ctm9w1
2. http://prntscr.com/ctma1w
3. http://prntscr.com/ctma4e

So We need to check on live server to check the exact issue, So can you please provide us all necessary details for live server.

Waiting for your reply here.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

1. RealURL:
Status > Done
Screenshot > http://prnt.sc/cw7h9h

2. DB Error
Status > Done

3. Error Log: New Error
Status > Done

**Note**  - We have updated the files on the Git, So please check it.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello

thanks for your fixes. I will chck them and give you feedback asap.

Regards,
Angelo

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 

Can you tell us after your holidays, what you had to do to make it work on our own development server? Thank you very much!

Best regards,
Michel

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
I hope you are doing good.

Thank you for your message. We have uploaded all the latest files on Dev server too, So now on Dev server all working fine. Please also check at your end.

Regards. Thanks!
