### ISSUE TITLE
Make EXT:netc_bakershop compatible with TYPO3 CMS Version 8.7

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#36]
Hello Jignesh

could you please adapt and upgrade the actual EXT:netc_bakershop to completely work with TYPO3 CMS Version 8.7.

I will send you all the access data with the upgraded V8.7 version by mail with all necessary informations so you can upgrade directly in the right website with real content.

Can you please tell me until when you think you could do this work?

Thank you very much for your feedback.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Greetings of the day!

I hope you are doing good.

**#Compatibility to TYPO3 8.X**
**Status**: Done
**Screenshots**: Please find following screenshots of the front end functionality.

1. Listing - https://prnt.sc/ha6e1w
2. Select Product - https://prnt.sc/ha6e6r
3. Confirm Product - https://prnt.sc/ha6eey
4. Address information - https://prnt.sc/ha6f1t
5. Payment Option - https://prnt.sc/ha6fc7
6. Bill - https://prnt.sc/ha6fh9
7. Message - https://prnt.sc/ha6flw
8. Mail - https://prnt.sc/ha6fxq

We have checked the compatibility with the following checklist.

1. Real-URL for extension
2. Functionality testing
3. Confirmation Mail
4. Install tool TCA migrations
5. check for the deprecated functions from install tool and log

**Question**: Do we need to upload our last changes to the repository or not?

Please also review this from your end and share your feedback with us.

Regards.

**Comment by angeloprevitali** [comment]
Good morning Jignesh

thanks for your works. We will check it and give you feedback asap.

For the moment please do not upload the untested version on GitHub. First I would like to check it :)

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your quick message.

Okay, Sure.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignseh

**all the images on the french website** on the list and detail pages gets not displaed in the FE even if the images are localised in the BE. 

Can you fix this?

**Example german list view products, which is ok:** 
http://swissbakerv8.netconsult.ch/de/ueber-uns/promo-shop/werbung/verkaufstafeln/

**Example in frech list view where the images are missing:**
http://swissbakerv8.netconsult.ch/fr/la-bcs/promoshop/publicite/tableaux-de-vente/

**Example german DETAIL view products, which is ok:** 
http://swissbakerv8.netconsult.ch/de/ueber-uns/promo-shop/werbung/verkaufstafeln/show/Products/a3-magnetrahmen-2er-packung/

**Example in frech DETAIL view where the images are missing:**
http://swissbakerv8.netconsult.ch/fr/la-bcs/promoshop/publicite/tableaux-de-vente/show/Products/a3-magnetrahmen-2er-packung/

Thanks.

Regards,
Angelo

**Comment by angeloprevitali** [comment]
See also

https://github.com/NetConsultAG/netc_bakershop/issues/37

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks for your work. Everything looks good.

Regards,
Angelo
