### ISSUE TITLE
V8: Link to the cart in sidebar isn't working on german and french language

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakershop#37]
Hello Jignesh

the link in the sidebar to the cart isn't working in bough languages on the TYPO3 CMS version 8.7LTS

https://prnt.sc/hb5ndt

Can you fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Greetings of the day!

**Status**: Done
**Comment**: We have set the link. Now it'll show in both languages. You can configure the page link from here: https://prnt.sc/hb7uo5
Screenshots:
DE: https://prnt.sc/hb8pk5 
FR: https://prnt.sc/hb8ve0

**Note**: I have set the link on it. Now it will work in both languages. 
You can configure it from here 
Backend: https://prnt.sc/hb7uo5

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks for your work. Looks good.

Regards,
Angelo
