### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by jigneshnitsan** [NetConsultAG/netc_bakershop#4]
1. Cart Menu - Total number of products.
Desc > call up a first page, I click on a product, add 3 pcs. in the cart. the care menu doesn't showing the number of products in cart. See this screenshot - http://prntscr.com/bvksym

2. In bakend you have set 17% but it shows 0%

3. VAT Calculation
Desc > Always all inclusive the vat. Just on the end the vat has to be deducted from the total price. this infors must come in the confirmations mails, too.

For e.g. 
Total        100
VAT(17%)      17  
------------------------------------
Total         100

4. 
In the cart there should NOT be the vat displayed. This should only come in the final page with the summary of all prodcuts before submitting the whole cart.
http://prntscr.com/bvktoa - This column for the vat is NOT necessary to be displayed on the cart. just in the final summary page

5. Show attributes in Cat summary and order summary - http://prntscr.com/bvkuc9 here - http://prntscr.com/bvkuqa

6. Shipping cost should also show in confirmation email

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

From the above point for #3 Vat Calculation, I have one query.
At the end we are showing the Total with including VAT - http://prntscr.com/bvmbx3 So when we show the VAT will it also include the "Postversand" & "Rechnung" in the VAT calculation. For e.g. If I purchased 2 the products with total CHF 10. So Total = 10 ( Inc. VAT ) and the value for "Postversand" = 2 & "Rechnung" = 2, Then the Total = 14 Then how the VAT will be calculated? Will it calculated with only product i.e.  CHF 10  or will it be calculated on CHF 14 (Including Post & Rechnung values).

Let me know your reply for the same.

Regards.

**Comment by michelrossier** [comment]
@jigneshnitsan Hi Jignesh, yes the VAT is included in all elements. So it has to be displayed for the whole sum. In your example the VAT should be shown for the CHF 14, (because the shipping includes VAT too).

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali  & @michelrossier 

Please find our update as following.

1. Cart Menu - Total number of products.
Status: Done
Screenshot > http://prntscr.com/bxqcrl

2. In bakend you have set 17% but it shows 0%
Status: Done
Screenshot: http://prntscr.com/bx5449 , http://prntscr.com/bx53zt

3. VAT Calculation
Status > Done
Screenshot > http://prntscr.com/bxodv4

4. In the cart there should NOT be the vat displayed. This should only come in the final page with the summary of all prodcuts before submitting the whole cart.
http://prntscr.com/bvktoa - This column for the vat is NOT necessary to be displayed on the cart. just in the final summary page
Status: Done
Screenshot: http://prntscr.com/bx51je , http://prntscr.com/bx53x2

5. Show attributes in Cat summary and order summary - http://prntscr.com/bvkuc9 here - http://prntscr.com/bvkuqa
Status: Done
Screenshot: http://prntscr.com/bx5320

Regards.
Thank You.
