### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by jigneshnitsan** [NetConsultAG/netc_bakershop#5]
1. now on the delivery fields there is a E-Mail Adress there. It should not be!

2. round to the nearest 5 cents, YES. 
EXAMPLE: 	217.78 => 217.80 
			217.74 = > 217.75 

3. Please add a checkbox for accepting the terms & conditions, please.

4. So by the selection of default image it should show on the product listing as well as product detail page: http://prntscr.com/bvnw64

5. Subproducts
Remove the whole Subproducts in the bakershop BE in the product and just add a Link like in the EXT:tx_news to get displayed additional products. In the xample of the tx_news it is called ""Related articles" that comes displayed in the frontend
if i would add an addiotnal product ot a product, you have  to add a prodcut first (titles, images, descritpions...) and after that you can add this product as a related product to a product

6. For some of the products price should only show after selecting the attribute else don't show the price and add to cart button. So need to give settings in backend.

**Comment by michelrossier** [comment]
#4 is not yet done, but defined in the open ticket https://github.com/NetConsultAG/netc_bakershop/issues/15 so I close this ticket here.

Else everything okay.
