### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by jigneshnitsan** [NetConsultAG/netc_bakershop#6]
1. on this screen i must have a button to return to the adresses again (a back button at the end)

2. Currency must be show like 12.00 globally for all places.

3. adjust the count of items showed for paging more prducts - adapt it by managing it dynamically like TypoScript constats

4. Sorting fields are not not Mulingual. Make it multilingual supported.

5. Backend text should also be multilinigual - Please just add the LLL file so we can make the transaltions.

6. i saw that also in the mail confirmations there are a lot of hardcoded things that must have a LLL

7. Currency should not be hardcoded.

8. It should never be a pid on the WHOLE extension that points to a hardcoded PID inside a template. Otherwise we got big problems in future, if the cart page gets changed by another pid. Can you please make this dynamic

9. BE - Remove this from plugin view - http://prntscr.com/bvnrkh & http://prntscr.com/bvnsnu

10. Remove the Email templates from the backend

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali  & @michelrossier 

Please find our update as following.

1. on this screen i must have a button to return to the adresses again (a back button at the end)
Status > Done 
Comment > Added back button in all cart steps.

2. Currency must be show like 12.00 globally for all places.
Status > Done 

3. Adjust the count of items showed for paging more prducts - adapt it by managing it dynamically like TypoScript constats
Status > Done 

4. Sorting fields are not not Mulingual. Make it multilingual supported.
Status > Done 
Sreenshot-BE > http://awesomescreenshot.com/0f061h3e41
Sreenshot-FE > http://awesomescreenshot.com/0fc61h3hf7

5. Backend text should also be multilinigual - Please just add the LLL file so we can make the transaltions.
Status > Done 

6. I saw that also in the mail confirmations there are a lot of hardcoded things that must have a LLL
Status > Done 

7. Currency should not be hardcoded.Currency should not be hardcoded.
Status > Done
Screenshot > http://awesomescreenshot.com/09b61h3w8d

8 . It should never be a pid on the WHOLE extension that points to a hardcoded PID inside a template. Otherwise we got big problems in future, if the cart page gets changed by another pid. Can you please make this dynamic
Status > Done

9. BE - Remove this from plugin view - http://prntscr.com/bvnrkh & http://prntscr.com/bvnsnu
Status > Done
Screenshot > http://awesomescreenshot.com/07161hmbc0

10. Remove the Email templates from the backend
Status > Done
Screenshot > http://awesomescreenshot.com/0d161hkw26

Regards.
Thank You.

**Comment by michelrossier** [comment]
Everything okay. Thanks.
