### ISSUE TITLE
Fields not stored

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakershop#9]
The fields "Firma", "Name" and "Vorname" are not stored properly and get lost when using the back button back to the cart and then back to the address page.

Recreate the problem:

1. Add a product into the cart
2. Go to the cart
3. Click Next and enter your address deetails
4. click submit
5. click back 
6. click back
7. click next

Now you are again on the address entry page and those 3 fields are empty:  "Firma", "Name" and "Vorname"

**Comment by jigneshnitsan** [comment]
Hello Michel

Status > Done
Screenshot > http://www.awesomescreenshot.com/00661x5ja7

Regards.

**Comment by michelrossier** [comment]
Thanks, that is good now!
